macro(Y_IsDigitNumber OutputBool InputStr)
    string(REGEX MATCH "^[0-9]+$" OutputBool ${InputStr})
endmacro()

macro(Y_GetNegativeValue OutputBool InputFlag)
    if (${InputFlag})
        set(${OutputBool} OFF)
    else ()
        set(${OutputBool} ON)
    endif ()
endmacro()

macro(Y_ParseArguments PREFIX)
    set(_options "")
    set(_one_value_keywords "")
    set(_multi_value_keywords "")
    cmake_parse_arguments(${PREFIX} ${_options} ${_one_value_keywords} ${_multi_value_keywords})
endmacro()
